### ISSUE TITLE
Expense request screen

### ISSUE THREAD

**Issue by tefloncoder** [ZenstillPhpTeam/zensilo#17]
Similar to leave request, employees should be able to submit their expense request. We need to have set of allowed expense heads (eg. Travel, Hotel stay, Lunch, Dinner, Client meeting etc.). The list of allowed expenses can be captured in the company profile screen. 
Any expense raised neeeds to be submitted for approval.

**Comment by gaikrish** [comment]
For the list of expense type , please user
1. Travel
2. Food
3. Accomodation
4. Team outing 
5. Team Lunch/Dinner
6. Others 

When user selects other it is mandatory that he/she provides details of the expense , for the other type of expenses the details is not mandatory.

For every expense , we need to capture the 'Date Incurred' and soft copy uploads if possible of the bills.
