### ISSUE TITLE
Email functionality (Intranet only)

### ISSUE THREAD

**Issue by tefloncoder** [ZenstillPhpTeam/zensilo#31]
Is it possible to integrate email functionality ? 

A user can mail status to PM or to clients and they can review it in their inbox

**Comment by vinogautam-t** [comment]
yes we have possible for this. We also have an ui for this.

![image](https://cloud.githubusercontent.com/assets/17449433/20710164/22398abc-b65f-11e6-9de4-ced89db4e809.png)
