### ISSUE TITLE
My Account - User profile

### ISSUE THREAD

**Issue by gaikrish** [ZenstillPhpTeam/zensilo#44]
The user profile picture is not being displayed.

**Comment by vinogautam-t** [comment]
fixed

**Comment by gaikrish** [comment]
![image](https://cloud.githubusercontent.com/assets/23522943/21804533/6b19c88e-d755-11e6-9050-1234c741a696.png)

please have a look at this screen shot , the profile image box is overlapping on the name and is coming below the top border
