### ISSUE TITLE
Leave requests

### ISSUE THREAD

**Issue by vinogautam-t** [ZenstillPhpTeam/zensilo#8]
Option to raise as well as send for approval, Approval screens

Estimate Start date
16/11/16

Estimate End date
17/11/16

**Comment by gaikrish** [comment]
We should have the following tyoes of leaves to start with 
1. Casual Leave
2. Sick Leave
3. Earned Leave/Annual Leave
4. Paternity Leave
5. Maternity Leave
6. Loss Of Pay Leave
7. Compensatory Leave

In addition to these types, if the user wants to add a different type of leave , should they be allowed to ? This is a question that need to be discussed and finalised.

The company admin (i.e., the admin of the company who buys this product) should be able to set the number of laves allowed against each one of these types of leaves for their company. 

When a user goes to the leave request page or sees his/her leave history, the following information should be displayed in the page somewhere.

Total no. of allowed leave: 

Total taken till date:

Remaining no. of days:
