### ISSUE TITLE
My Expenses - Issue in Delete

### ISSUE THREAD

**Issue by gaikrish** [ZenstillPhpTeam/zensilo#84]
Logged in as jai/jai .

Create a new expense.
Click on delete.
Close the pop-up that asks if you really want to delete.  

Expected Result: The expense should not be deleted.

Actual Result : The expense is deleted.

**Comment by gaikrish** [comment]
This is still happening. In the pop-up click on the 'x' - close , the expense is getting deleted.

**Comment by vinogautam-t** [comment]
Sorry. Just now code updated in live.
